[package]
name = "solana-client-example"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = "1.18.11"
solana-client = "1.18.11"
solana-program = "1.18.11" # For Pubkey and other useful types
borsh = "0.10.3"
tokio = { version = "1", features = ["full"] } 
