[workspace]
members = [
    "zk-program"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Your Name <your.email@example.com>"]

[workspace.metadata]
description = "Bonsol Calculator project with Risc0 and Solana integration" 
