[package]
name = "test-client"
version = "0.1.0"
edition = "2021"

[workspace]
# Empty workspace to make this a standalone package

[dependencies]
solana-client = "~2.0"
solana-sdk = "~2.0"
borsh = "0.10.3" 
